env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: latest
rules: {
  no-unused-vars: off,
  no-undef: off,
  indent: [warn, 2],
  quotes: [warn, single],
  space-in-parens: 1,
  prefer-destructuring: 0,
  prefer-const: 0
}
